### ISSUE TITLE
cannot connet to https://archive.org/download/pt711/PacketTracer7.1.1ForLinux64Bit.tar

### ISSUE THREAD

**Issue by Iqbal-29** [frzifus/docker-packet-tracer#1]
Hai, i`m new in docker and i want to try this project but i get this error even though i already create Internet Archive account.

![Screenshot from 2020-03-26 23-39-41](https://user-images.githubusercontent.com/62233284/77665805-1b8cc800-6fbb-11ea-85dc-54a8022415be.png)

Will help me with this error please.
Thank you.

**Comment by frzifus** [comment]
Hi, thanks for the report. it seems the archive doesn't exist anymore. packet-tracer is now available in version 7.3 as deb package for ubuntu 18.04. I'll have a closer look at it over the weekend and fix it.
